apiVersion: v1
kind: Pod # P 要大写
metadata:
  name: mwish-bot-another
  labels:
    creation_method: manual
    env: prod
    app: mwish-bot
spec:
  containers:
  - image: redis
    name: mredis-another
    ports:
    - containerPort: 6379
      protocol: TCP
      name: redis-port
    readinessProbe:
      exec:
        command:
        - redis-cli
        - get 5
